services:
  rest-server-service:
    image: rest-server:v1
    # or sepcify the build
    # build: .
    depends_on:
      - rest-server-db
    links:
      - "rest-server-db:db"
    ports:
      - 8000:8000
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - TOKEN_EXPIRE_MINUTES=${TOKEN_EXPIRE_MINUTES}
    networks:
      - rest-server-network
    # volumes:
    #   - ./:/usr/src/app:ro # bind mount
    # add reload for dev
    # command: uvicorn app.main:app --port 8000 --host=0.0.0.0 --reload
  
  rest-server-db:
    image: postgres:16.3-alpine3.20
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - rest-server-network
    volumes:
      - reset-server-db-volume:/var/lib/postgresql/data

  

networks:
  rest-server-network:
    driver: bridge

volumes:
  reset-server-db-volume:
    driver: local